theme: jekyll-theme-primer

title: "Hacker Code UK by Antonio Feijao UK"

description: "Online learning, training and educational material for white hackers, the good hackers!"

page.author: "Antonio Feijao UK"

author:
  name: "Antonio Feijao UK"
  email: "antoniofeijao@gmail.com"
  url: "https://www.antoniocloud.com"


#theme: jekyll-theme-hacker  # theme source https://github.com/pages-themes/hacker ## https://github.com/tocttou/hacker-blog
#theme: jekyll-theme-minimal
#theme: jekyll-theme-midnight


show_downloads: false

google_analytics:


baseurl: /

#source: .
#destination: ./_site
permalink: pretty
#paginate: 3
#paginate_path: /page/:num/

#defaults:
#  -
#    scope:
#      path: ""
#      type: "posts"
#    values:
#      layout: "post"

#future: true

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-toc

#markdown: kramdown


kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge
 parse_block_html: true
 
