theme: jekyll-theme-hacker
# theme source https://github.com/pages-themes/hacker

title: Hacker Code UK by Antonio Feijao UK

description: "Online learning, training and educational material for white hackers, the good hackers!"

#author:
#  name: "Antonio Feijao UK"
#  email: "antoniofeijao@gmail.com"
#  url: "https://www.antoniocloud.com"

show_downloads: false

google_analytics:

permalink: pretty

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

